image: tmaier/docker-compose:18

services:
  - docker:dind

stages:
  - build
  - test
  - package

before_script:
  - apk add --no-cache bash git

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.zip
      - dist/*.rb
      - dist/*.deb
      - dist/*.rpm
      - dist/*.txt

test-unit:
  stage: test
  script:
    - ./bin/test.sh oss
  artifacts:
    paths:
      - output/junit.xml
