# All available options: https://goreleaser.com/customization/
project_name: summon-conjur

before:
  hooks:
  - go mod download

builds:
- binary: summon-conjur
  env:
  - CGO_ENABLED=0
  goos:
  - darwin  # MacOS
  - windows
  - linux
  goarch:
  - amd64
  ldflags: []
  main: cmd/main.go

archives:
  - id: summon-conjur-release-archive
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - description: Conjur provider for Summon
    homepage: https://github.com/cyberark/summon-conjur
    url_template: https://github.com/cyberark/summon-conjur/releases/download/v{{.Version}}/summon-conjur-darwin-amd64.tar.gz
    install: |
      target = lib/"summon"
      target.install "summon-conjur"
    test: |
      system lib/"summon"/"summon-conjur", "-V"

    github:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: CyberArk
    homepage: https://github.com/cyberark/summon-conjur
    maintainer: Conjur Maintainers <conj_maintainers@cyberark.com>

    description: Conjur provider for Summon
    recommends:
      - summon
    license: MIT
    formats:
    - deb
    - rpm
    bindir: /usr/local/lib/summon  # where the binary is placed, default summon provider dir

release:
  disable: true
  prerelease: auto
