version: '2'
services:
  builder:
    build: .
    image: summon-conjur-builder
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/go/src/github.com/cyberark/summon-conjur/output
    environment:
      GOOS:
      GOARCH:

  postgres:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.8.1-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres

  cuke-master:
    image: registry.tld/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    ports:
      - 443

  test:
    build: .
    image: summon-conjur-tester
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: /bin/bash
    command: './test-entrypoint.sh'
    volumes:
      - ./output:/go/src/github.com/cyberark/summon-conjur/output
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health

  dev:
    build: .
    image: summon-conjur-dev
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: /bin/bash
    command: './test-entrypoint.sh'
    volumes:
      - .:/go/src/github.com/cyberark/summon-conjur
      - ../conjur-api-go:/go/src/github.com/cyberark/conjur-api:ro
      
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
