version: '2'
services:
  conjur:
    image: cyberark/conjur:1.3
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres

  postgres:
    image: postgres:9.3

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: summon-conjur-tester
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: /bin/bash
    command: './bin/test-entrypoint.sh'
    volumes:
      - ./output:/summon-conjur/output
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:

  dev:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: summon-conjur-dev
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: /bin/bash
    command: './bin/test-entrypoint.sh'
    volumes:
      - .:/summon-conjur
      - ../conjur-api-go:/cconjur-api-go:ro

    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
