version: '2'
services:
  cuke-master:
    image: registry.tld/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    ports:
      - 443

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: summon-conjur-tester
    ports:
        - "8080"
    entrypoint: /bin/bash
    command: './bin/test-entrypoint.sh'
    volumes:
      - ./output:/summon-conjur/output
    environment:
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
