version: '2'
services:
  builder:
    build: .
    image: summon-conjur-builder
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/go/src/github.com/cyberark/summon-conjur/output
    environment:
      GOOS:
      GOARCH:

  postgres:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.1.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - postgres

  cuke-master:
    container_name: summon-conjur-v4
    image: registry.tld/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    ports:
      - 443

  tester:
    build: .
    image: summon-conjur-tester
    ports:
        - "8080"
    depends_on:
      - conjur
    entrypoint: /bin/bash
    command: './test-entrypoint.sh'
    volumes:
      - .:/go/src/github.com/cyberark/summon-conjur
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY:
      CONJUR_V4_APPLIANCE_URL: https://cuke-master/api
      CONJUR_V4_HEALTH_URL: https://cuke-master/health
      CONJUR_V4_ACCOUNT: cucumber
      CONJUR_V4_AUTHN_LOGIN: admin
